from controllers.author_controller import AuthorController
from controllers.shelf_controller import ShelfController
from controllers.member_controller import MemberController
from controllers.book_controller import BookController
